#! /usr/bin/env python

import pointy
import sys

def run(port, host, not_public):
    app = pointy.getapp(port, host, not_public)
    app.run()

if __name__ == "__main__":
    if sys.argv[-1] == 'local':
        run(port=5000, host='127.0.0.1', not_public=False)
    elif sys.argv[-1] == 'public':
        run(port=5000, host='0.0.0.0', not_public=True)
    else:
        print 'must give argument local or private'
